import {objectives} from './syllabus.mjs';
import {KEY,AREAS as EXAM_AREAS,decode,remaining,pick,grade,reset,shuffle} from './engine.mjs';
import {books} from '../output/markdown/books.mjs';
const AREAS=books.map(b=>({id:b.id,title:b.title,description:b.description,code:b.id}));
const practiceURL=new URL('./',import.meta.url);
const questionBook=q=>q.area==='business'?(Number(q.syllabus.split('.')[1])>=4?'06':'05'):(q.syllabus==='3.1.1.3'||Number(q.syllabus.split('.')[1])>=6?'04':'03');
const root=document.querySelector('#app');
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let bank={},area=null,mode='quiz',current=null,order=[],submitted=false,selection=null,page=1,topic='',storageWarning='';
let state={version:1,solved:{}};
try{state=decode(localStorage.getItem(KEY));}catch{storageWarning='저장된 진도를 읽을 수 없어 이번 학습은 임시로 진행합니다. 기존 기록은 덮어쓰지 않습니다.';}
function read(){if(storageWarning)return state;try{state=decode(localStorage.getItem(KEY));}catch{storageWarning='진도를 읽을 수 없어 임시로 진행합니다.';}return state;}
function persist(){if(storageWarning)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageWarning='진도를 저장할 수 없어 새로고침하면 이번 기록이 사라질 수 있습니다.';}}
function warning(){return storageWarning?`<p class="error" role="alert">${escape(storageWarning)}</p>`:'';}
function counts(id){const qs=bank[id];return {total:qs.length,done:qs.length-remaining(qs,state).length};}
function navigate(id,newMode='quiz',replace=false){area=id;mode=newMode;page=1;topic='';current=null;submitted=false;const url=new URL(id?`${id}/`:'./',practiceURL);if(id)url.searchParams.set('mode',mode);history[replace?'replaceState':'pushState'](null,'',url);render();}
function home(){root.innerHTML=`${warning()}<section class="intro"><div class="eyebrow">V4.0K · 객관식 연습</div><h1>한 문제씩,<br>내 것으로 만드세요.</h1><p>한 번 맞히면 완료입니다. 남은 문제 중에서 다음 문제를 무작위로 불러옵니다.</p><div class="total"><strong>${Object.values(bank).flat().length}개</strong><span>교재 6권 · 객관식 연습문제</span></div></section><div class="area-grid">${AREAS.map(a=>{const s=counts(a.id);return `<button class="area-card" data-area="${a.id}"><div class="card-top"><span class="book">${a.code}</span><span>${s.total}문항</span></div><h2>${a.title}</h2><p>${a.description}</p><div class="progress-label"><span>한 번 이상 정답</span><strong>${s.done} / ${s.total}개</strong></div><progress aria-label="${a.title} 완료" value="${s.done}" max="${s.total}"></progress><div class="card-action"><span>${s.total?'학습 시작':'문제 준비 중'}</span><span>→</span></div></button>`;}).join('')}</div><section class="guide"><h2>세 가지 방법으로 공부하세요</h2><p><strong>전체모드</strong> · 문제와 보기를 순서대로 읽습니다.<br><strong>설명모드</strong> · 정답과 해설을 함께 읽습니다.<br><strong>문제풀기모드</strong> · 랜덤으로 풀고, 한 번 맞힌 문제는 제외합니다.</p><p>과목 안의 초기화 버튼으로 해당 과목을 처음부터 다시 풀 수 있습니다.</p></section>`;root.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>navigate(b.dataset.area));}
function render(){read();if(!area)return home();const a=AREAS.find(a=>a.id===area);const s=counts(area);root.innerHTML=`${warning()}<div class="quiz-nav"><button id="home" class="text-button">← 과목 선택</button><button id="reset" class="text-button">이 과목 진도 초기화</button></div><div class="quiz-heading"><div class="eyebrow">${a.code} · V4.0K</div><h1>${a.title}</h1><div class="progress-label"><span>완료 ${s.done}개 / 전체 ${s.total}개</span><span>남은 문제 ${s.total-s.done}개</span></div><progress aria-label="학습 완료" value="${s.done}" max="${s.total}"></progress></div><nav class="mode-tabs" aria-label="학습 모드">${[['all','전체모드'],['explain','설명모드'],['quiz','문제풀기모드']].map(([id,title])=>`<button data-mode="${id}" aria-pressed="${mode===id}">${title}</button>`).join('')}</nav><div id="panel"></div>`;root.querySelector('#home').onclick=()=>navigate(null);root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>navigate(area,b.dataset.mode));root.querySelector('#reset').onclick=resetDialog;if(mode==='quiz')renderQuiz();else renderReading();}
function questionContext(q){
 const areaTitle=EXAM_AREAS.find(a=>a.id===q.area).title;
 const objective=objectives[q.syllabus];
 const path=[...new Set([areaTitle,objective,q.topic])];
 return `<aside class="question-context" aria-label="문제 카테고리와 출제기준"><div class="category-path"><strong>카테고리</strong><span>${path.map(escape).join(' <span class="category-separator" aria-hidden="true">›</span> ')}</span></div><div class="syllabus-detail"><strong>출제기준</strong><span>V4.0K · ${escape(q.syllabus)}<br>${escape(objective)} <small>(학습목표 요약)</small></span></div></aside>`;
}
function source(q){return `<p class="syllabus-text"><strong>출제기준</strong> V4.0K · ${escape(q.syllabus)} · ${escape(objectives[q.syllabus])}</p>`;}
function renderQuiz(){const panel=root.querySelector('#panel');if(!bank[area].length){panel.innerHTML='<section class="complete"><h2>문제 준비 중입니다.</h2><p>이 교재의 등록된 문제가 아직 없습니다.</p></section>';return;}if(!current){current=pick(bank[area],state);order=shuffle([0,1,2,3]);submitted=false;selection=null;}
 if(!current){panel.innerHTML=`<section class="complete"><div class="completion-mark">✓</div><h2>이 과목을 모두 맞혔습니다!</h2><p>${bank[area].length}문항을 한 번 이상 맞혔습니다.<br>설명모드로 복습하거나 진도를 초기화해 다시 풀어 보세요.</p><button class="primary" id="review">설명모드로 복습</button></section>`;panel.querySelector('#review').onclick=()=>navigate(area,'explain');return;}
 const q=current;panel.innerHTML=`<section class="question-card" data-question-id="${q.id}"><div class="question-meta"><span>${escape(q.topic)}</span><span>${q.id}</span></div>${questionContext(q)}<h2 id="prompt">${escape(q.prompt)}</h2><form id="answer-form"><fieldset ${submitted?'disabled':''}><legend class="sr-only">정답 하나를 선택하세요</legend>${order.map((original,i)=>`<label class="option ${submitted&&original===q.answer?'correct':submitted&&selection===original?'wrong':''}"><input type="radio" name="answer" value="${original}" ${selection===original?'checked':''}><span class="option-number">${i+1}</span><span>${escape(q.options[original])}${submitted?(original===q.answer?'<strong class="answer-tag">✓ '+(selection===original?'내 선택 · 정답':'정답')+'</strong>':selection===original?'<strong class="answer-tag">✕ 내 선택 · 오답</strong>':''):'<strong class="selection-tag">내 선택</strong>'}</span></label>`).join('')}</fieldset>${submitted?'':'<button class="primary" id="submit" disabled>정답 확인</button>'}</form>${submitted?`<section class="feedback" tabindex="-1" role="status"><div class="result ${selection===q.answer?'':'incorrect'}">${selection===q.answer?'정답입니다. 다음 출제에서 제외됩니다.':'오답입니다. 이 문제는 다시 출제됩니다.'}</div><h3>정답과 해설</h3><p><strong>${escape(q.options[q.answer])}</strong></p><p>${escape(q.explanation)}</p>${source(q)}<button class="primary" id="next">다음 랜덤 문제 →</button></section>`:''}</section>`;
 if(submitted){panel.querySelector('#next').onclick=()=>{const previous=current.id;read();current=pick(bank[area],state,previous);submitted=false;selection=null;order=shuffle([0,1,2,3]);render();root.querySelector('#prompt')?.scrollIntoView({block:'center'});};}
 else{const form=panel.querySelector('form');form.onchange=()=>{panel.querySelector('#submit').disabled=false;};form.onsubmit=async e=>{e.preventDefault();if(submitted)return;const raw=new FormData(form).get('answer');if(raw===null)return;const selected=Number(raw);selection=selected;submitted=true;const update=()=>{read();grade(state,q,selected);persist();};if(navigator.locks){await navigator.locks.request(KEY,update);}else update();render();if(current===q&&mode==='quiz')root.querySelector('.feedback')?.focus();};}
}
function renderReading(){const panel=root.querySelector('#panel');const topics=[...new Set(bank[area].map(q=>q.topic))];const qs=bank[area].filter(q=>!topic||q.topic===topic);const pages=Math.max(1,Math.ceil(qs.length/20));page=Math.min(page,pages);panel.innerHTML=`<div class="reading-intro"><h2>${mode==='explain'?'정답과 해설로 복습하기':'문제와 보기 전체 읽기'}</h2><p>읽기 모드는 진도를 바꾸지 않습니다. ${qs.length}문항 중 ${qs.length?(page-1)*20+1:0}–${Math.min(page*20,qs.length)}번을 보고 있습니다.</p><label for="topic">주제</label> <select id="topic"><option value="">모든 주제</option>${topics.map(t=>`<option ${topic===t?'selected':''}>${escape(t)}</option>`).join('')}</select></div><div class="reading-list">${qs.slice((page-1)*20,page*20).map((q,i)=>`<article class="question-card"><div class="question-meta"><span>${(page-1)*20+i+1}번 · ${escape(q.topic)}</span><span>${q.id}</span></div>${questionContext(q)}<h2>${escape(q.prompt)}</h2><ol class="reading-options">${q.options.map((o,n)=>`<li class="${mode==='explain'&&n===q.answer?'reading-correct':''}">${escape(o)}${mode==='explain'&&n===q.answer?' <strong>✓ 정답</strong>':''}</li>`).join('')}</ol>${mode==='explain'?`<section class="reading-explanation"><h3>정답과 해설</h3><p>${escape(q.explanation)}</p>${source(q)}</section>`:''}</article>`).join('')}</div><nav class="pagination" aria-label="문제 목록 페이지"><button id="prev-page" ${page===1?'disabled':''}>← 이전</button><label>페이지 <select id="page">${Array.from({length:pages},(_,i)=>`<option value="${i+1}" ${page===i+1?'selected':''}>${i+1} / ${pages}</option>`).join('')}</select></label><button id="next-page" ${page===pages?'disabled':''}>다음 →</button></nav>`;panel.querySelector('#topic').onchange=e=>{topic=e.target.value;page=1;renderReading();};const go=n=>{page=n;renderReading();root.querySelector('.reading-intro').scrollIntoView({block:'start'});};panel.querySelector('#prev-page').onclick=()=>go(page-1);panel.querySelector('#next-page').onclick=()=>go(page+1);panel.querySelector('#page').onchange=e=>go(Number(e.target.value));}
function resetDialog(){const questions=bank[area];const a=AREAS.find(a=>a.id===area);const d=document.createElement('dialog');d.innerHTML=`<h2>진도를 초기화할까요?</h2><p>${a.title}의 정답 기록을 지웁니다. 다른 과목의 진도는 유지됩니다.</p><div class="dialog-actions"><button id="cancel">취소</button><button id="confirm">이 과목 초기화</button></div>`;document.body.append(d);d.addEventListener('close',()=>d.remove());d.querySelector('#cancel').onclick=()=>d.close();d.querySelector('#confirm').onclick=async()=>{const update=()=>{read();reset(state,questions);persist();};if(navigator.locks)await navigator.locks.request(KEY,update);else update();current=null;submitted=false;d.close();render();};d.showModal();}
function fromURL(){const params=new URL(location.href).searchParams;area=location.pathname.match(/\/practice\/(0[1-6])(?:\/|$)/)?.[1] || ({business:'05','systems-security':'03'}[params.get('area')] || (AREAS.some(a=>a.id===params.get('area'))?params.get('area'):null));mode=['all','explain','quiz'].includes(params.get('mode'))?params.get('mode'):'quiz';current=null;submitted=false;page=1;topic='';render();}
addEventListener('popstate',fromURL);
addEventListener('storage',e=>{if(e.key===KEY&&Object.keys(bank).length===AREAS.length){read();if(current&&state.solved[`${current.id}@${current.revision}`]&&!submitted)current=null;render();}});
try{const loaded=Object.fromEntries(await Promise.all(EXAM_AREAS.map(async a=>{const r=await fetch(new URL(`data/${a.id}.json`,import.meta.url),{cache:'no-cache'});if(!r.ok)throw Error('문제 파일을 불러올 수 없습니다.');const qs=await r.json();if(!Array.isArray(qs)||!qs.length)throw Error('문제 데이터가 비어 있습니다.');return [a.id,qs];})));bank=Object.fromEntries(AREAS.map(a=>[a.id,Object.values(loaded).flat().filter(q=>questionBook(q)===a.id)]));fromURL();}catch(e){root.innerHTML=`<section class="error"><h1>문제를 불러오지 못했습니다</h1><p>${escape(e.message)} 연결 상태를 확인하고 새로고침해 주세요.</p><button onclick="location.reload()">다시 불러오기</button></section>`;}
