import { readFile, mkdir, writeFile, copyFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const languages = ['core', 'markup', 'css', 'clike', 'javascript', 'python', 'sql', 'java', 'c', 'cpp', 'csharp', 'bash', 'json'];
const parts = await Promise.all(languages.map(name => readFile(new URL(`node_modules/prismjs/components/prism-${name}.min.js`, root), 'utf8')));
await mkdir(new URL('shared/vendor/', root), { recursive: true });
await writeFile(new URL('shared/vendor/prism.mjs', root), '// Prism.js — MIT license; generated by scripts/build-syntax.mjs\nif(typeof window!=="undefined")window.Prism={manual:true,disableWorkerMessageHandler:true};\n' + parts.join('\n') + '\nexport default Prism;\n');
await copyFile(new URL('node_modules/prismjs/LICENSE', root), new URL('shared/vendor/prism-LICENSE.txt', root));
